language: node_js
node_js:
- '0.10'
services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: WUNZS4/oODoakNggAW2RdCbLVeoeCYZcQLs0PFqsN9q5uxAh925iN3IlanjWl2pnNrd+3XSRsDoZFsUig+jACsC3YOwrjJZZ2JhB0Gn7ae3X5RHEvovdAT5BbnDrZ0P4yCFgrdtmh55DKI+qX5/HcAqzZ5rR7K/HGmHes3w/R3Q=
