language: node_js
node_js:
- '5.6'
services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: Z/ar/K+FjEKNS6dYRhOiTXFY4QUf4tEJeDD4UvgrvNMQXNldCN5cZZeIXLyWBHm6pntPj7djEXC8xG/HHA/EGz71OL6PfXNZ0WKPZHoRGCmb+Q4cr48UKVRmqwVHWmeR/HDOdlCya0macKSmpO3RzUWh0rKvUMR5+6UHrtJxjBA=
